#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/90-crypto/arith.tex					\
	chapters/90-crypto/ff.tex					\
	chapters/90-crypto/elliptisch.tex				\
	chapters/90-crypto/aes.tex					\
	chapters/90-crypto/chapter.tex
