#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ifs =						\
	papers/ifs/packages.tex					\
	papers/ifs/main.tex					\
	papers/ifs/references.bib				\
	papers/ifs/teil0.tex					\
	papers/ifs/teil1.tex					\
	papers/ifs/teil2.tex					\
	papers/ifs/teil3.tex

