#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-mceliece =						\
	papers/mceliece/packages.tex					\
	papers/mceliece/main.tex					\
	papers/mceliece/references.bib				\
	papers/mceliece/einleitung.tex					\
	papers/mceliece/aufbau.tex					\
	papers/mceliece/funktionsweise.tex					\
	papers/mceliece/fazit.tex

