#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-mceliece =						\
	papers/mceliece/packages.tex					\
	papers/mceliece/main.tex					\
	papers/mceliece/references.bib				\
	papers/mceliece/teil0.tex					\
	papers/mceliece/teil1.tex					\
	papers/mceliece/teil2.tex					\
	papers/mceliece/teil3.tex

