#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-punktgruppen =	\
	papers/punktgruppen/packages.tex \
	papers/punktgruppen/main.tex \
	papers/punktgruppen/intro.tex \
	papers/punktgruppen/symmetry.tex \
	papers/punktgruppen/crystals.tex \
	papers/punktgruppen/piezo.tex \
	papers/punktgruppen/references.bib \
    papers/punktgruppen/tikz/combine-symmetries.tex \
	papers/punktgruppen/tikz/lattice.tex \
	papers/punktgruppen/tikz/piezo-atoms.tex \
	papers/punktgruppen/tikz/piezo.tex \
	papers/punktgruppen/tikz/projections.tex
