#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-punktgruppen =	\
	papers/punktgruppen/packages.tex \
	papers/punktgruppen/main.tex \
	papers/punktgruppen/intro.tex \
	papers/punktgruppen/symmetry.tex \
	papers/punktgruppen/crystals.tex \
	papers/punktgruppen/piezo.tex \
	papers/punktgruppen/references.bib \
	paers/punktgruppen/tikz/atoms-grid-force.tex \
	paers/punktgruppen/tikz/atoms-grid-still.tex \
	paers/punktgruppen/tikz/atoms-piezo-force-horizontal.tex \
	paers/punktgruppen/tikz/atoms-piezo-force-vertical.tex \
	paers/punktgruppen/tikz/atoms-piezo-still.tex \
	paers/punktgruppen/tikz/combine-symmetries.tex \
	paers/punktgruppen/tikz/lattice.tex \
	paers/punktgruppen/tikz/piezo-atoms.tex \
	paers/punktgruppen/tikz/piezo.tex \
	paers/punktgruppen/tikz/projections.tex \
	paers/punktgruppen/tikz/stereographic-projections.tex \
	paers/punktgruppen/tikz/symmetric-shapes.tex
