#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-punktgruppen =						\
	papers/punktgruppen/packages.tex					\
	papers/punktgruppen/main.tex					\
	papers/punktgruppen/references.bib				\
	papers/punktgruppen/teil0.tex					\
	papers/punktgruppen/teil1.tex					\
	papers/punktgruppen/teil2.tex					\
	papers/punktgruppen/teil3.tex

