#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-spannung =						\
	papers/spannung/packages.tex					\
	papers/spannung/main.tex					\
	papers/spannung/references.bib				\
	papers/spannung/teil0.tex					\
	papers/spannung/teil1.tex					\
	papers/spannung/teil2.tex					\
	papers/spannung/teil3.tex

