
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter9 =								\
	../slides/9/google.tex						\
	../slides/9/markov.tex						\
	../slides/9/irreduzibel.tex					\
	../slides/9/stationaer.tex					\
	../slides/9/pf.tex						\
	../slides/9/potenz.tex						\
	../slides/9/pf/positiv.tex					\
	../slides/9/pf/primitiv.tex					\
	../slides/9/pf/trennung.tex					\
	../slides/9/pf/vergleich.tex					\
	../slides/9/pf/vergleich3d.tex					\
	../slides/9/pf/dreieck.tex					\
	../slides/9/pf/folgerungen.tex					\
	../slides/9/parrondo/erwartung.tex				\
	../slides/9/parrondo/spiela.tex					\
	../slides/9/parrondo/spielb.tex					\
	../slides/9/parrondo/spielbmod.tex				\
	../slides/9/chapter.tex

