
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter9 =								\
	../slides/9/google.tex						\
	../slides/9/markov.tex						\
	../slides/9/irreduzibel.tex					\
	../slides/9/stationaer.tex					\
	../slides/9/pf.tex						\
	../slides/9/chapter.tex

