#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-erdbeben =						\
	papers/erdbeben/packages.tex					\
	papers/erdbeben/main.tex					\
	papers/erdbeben/references.bib				\
	papers/erdbeben/teil0.tex					\
	papers/erdbeben/teil1.tex					\
	papers/erdbeben/teil2.tex					\
	papers/erdbeben/teil3.tex

