
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter3 =								\
	../slides/3/motivation.tex					\
	../slides/3/inverse.tex						\
	../slides/3/polynome.tex					\
	../slides/3/division.tex					\
	../slides/3/division2.tex					\
	../slides/3/ringstruktur.tex					\
	../slides/3/teilbarkeit.tex					\
	../slides/3/ideal.tex						\
	../slides/3/idealverband.tex					\
	../slides/3/maximalideal.tex					\
	../slides/3/quotientenring.tex					\
	../slides/3/faktorisierung.tex					\
	../slides/3/faktorzerlegung.tex					\
	../slides/3/einsetzen.tex					\
	../slides/3/maximalergrad.tex					\
	../slides/3/minimalbeispiel.tex					\
	../slides/3/fibonacci.tex					\
	../slides/3/minimalpolynom.tex					\
	../slides/3/drehmatrix.tex					\
	../slides/3/drehfaktorisierung.tex				\
	../slides/3/operatoren.tex					\
	../slides/3/adjunktion.tex					\
	../slides/3/adjalgebra.tex					\
	../slides/3/wurzel2.tex						\
	../slides/3/chapter.tex

