
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter5 =								\
	../slides/5/motivation.tex					\
	../slides/5/charpoly.tex					\
	../slides/5/kernbild.tex					\
	../slides/5/ketten.tex						\
	../slides/5/dimension.tex					\
	../slides/5/folgerungen.tex					\
	../slides/5/injektiv.tex					\
	../slides/5/nilpotent.tex					\
	../slides/5/eigenraeume.tex					\
	../slides/5/zerlegung.tex					\
	../slides/5/normalnilp.tex					\
	../slides/5/jordan.tex						\
	../slides/5/chapter.tex

