
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter5 =								\
	../slides/5/verzerrung.tex					\
	../slides/5/motivation.tex					\
	../slides/5/charpoly.tex					\
	../slides/5/kernbildintro.tex					\
	../slides/5/kernbilder.tex					\
	../slides/5/kernbild.tex					\
	../slides/5/ketten.tex						\
	../slides/5/dimension.tex					\
	../slides/5/folgerungen.tex					\
	../slides/5/injektiv.tex					\
	../slides/5/nilpotent.tex					\
	../slides/5/eigenraeume.tex					\
	../slides/5/zerlegung.tex					\
	../slides/5/normalnilp.tex					\
	../slides/5/bloecke.tex						\
	../slides/5/jordanblock.tex					\
	../slides/5/jordan.tex						\
	../slides/5/reellenormalform.tex				\
	../slides/5/cayleyhamilton.tex					\
									\
	../slides/5/spektrum.tex					\
	../slides/5/normal.tex						\
	../slides/5/unitaer.tex						\
									\
	../slides/5/konvergenzradius.tex				\
	../slides/5/krbeispiele.tex					\
	../slides/5/spektralgelfand.tex					\
	../slides/5/Aiteration.tex					\
	../slides/5/satzvongelfand.tex					\
									\
	../slides/5/stoneweierstrass.tex				\
	../slides/5/potenzreihenmethode.tex				\
	../slides/5/logarithmusreihe.tex				\
	../slides/5/exponentialfunktion.tex				\
	../slides/5/hyperbolisch.tex					\
	../slides/5/chapter.tex

