#
# Makefile.inc -- Makefile dependencies for chapter 0.5
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/05-zahlen/natuerlich.tex				\
	chapters/05-zahlen/ganz.tex					\
	chapters/05-zahlen/rational.tex					\
	chapters/05-zahlen/reell.tex					\
	chapters/05-zahlen/komplex.tex					\
	chapters/05-zahlen/chapter.tex
