#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter6 =								\
	../slides/6/punktgruppen/ebene.tex				\
	../slides/6/punktgruppen/semidirekt.tex				\
	../slides/6/punktgruppen/c.tex					\
	../slides/6/punktgruppen/d.tex					\
	../slides/6/punktgruppen/p.tex					\
	../slides/6/punktgruppen/chemie.tex				\
	../slides/6/punktgruppen/aufspaltung.tex			\
									\
	../slides/6/produkte/frei.tex					\
	../slides/6/produkte/direkt.tex					\
									\
	../slides/6/normalteiler/normal.tex				\
	../slides/6/normalteiler/konjugation.tex			\
									\
	../slides/6/permutationen/matrizen.tex				\
									\
	../slides/6/darstellungen/definition.tex			\
	../slides/6/darstellungen/charakter.tex				\
	../slides/6/darstellungen/summe.tex				\
	../slides/6/darstellungen/irreduzibel.tex			\
	../slides/6/darstellungen/schur.tex				\
	../slides/6/darstellungen/skalarprodukt.tex			\
	../slides/6/darstellungen/zyklisch.tex				\
									\
	../slides/6/chapter.tex

