#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2020 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/10-matrizenvektoren/chapter.tex
