#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2020 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/10-matrizenvektoren/linear.tex				\
	chapters/10-matrizenvektoren/strukturen.tex			\
	chapters/10-matrizenvektoren/gruppen.tex			\
	chapters/10-matrizenvektoren/ringe.tex				\
	chapters/10-matrizenvektoren/algebren.tex			\
	chapters/10-matrizenvektoren/koerper.tex			\
	chapters/10-matrizenvektoren/hadamard.tex			\
	chapters/10-matrizenvektoren/uebungsaufgaben/1001.tex		\
	chapters/10-matrizenvektoren/uebungsaufgaben/1002.tex		\
	chapters/10-matrizenvektoren/chapter.tex
