#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/80-crypto/ff.tex					\
	chapters/80-crypto/aes.tex					\
	chapters/80-crypto/rs.tex					\
	chapters/80-crypto/chapter.tex
