#
# Makefile -- build images
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	ideale.pdf gausszahlen.pdf strukturen.pdf

ideale.pdf:	ideale.tex
	pdflatex ideale.tex

gausszahlen.pdf:	gausszahlen.tex
	pdflatex gausszahlen.tex

strukturen.pdf:	strukturen.tex
	pdflatex strukturen.tex
