#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-000template =						\
	papers/000template/packages.tex					\
	papers/000template/main.tex					\
	papers/000template/references.bib				\
	papers/000template/einleitung.tex				\
	papers/000template/teil1.tex					\
	papers/000template/teil2.tex					\
	papers/000template/teil3.tex

