#
# Makefile.inc -- Makefile dependencies for chapter 2
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/20-polynome/definitionen.tex				\
	chapters/20-polynome/vektoren.tex				\
	chapters/20-polynome/matrizen.tex				\
	chapters/20-polynome/minimalpolynom.tex				\
	chapters/20-polynome/chapter.tex
