#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter5 =								\
	../slides/7/symmetrien.tex					\
	../slides/7/algebraisch.tex					\
	../slides/7/parameter.tex					\
	../slides/7/mannigfaltigkeit.tex				\
	../slides/7/sl2.tex						\
	../slides/7/drehung.tex						\
	../slides/7/drehanim.tex					\
	../slides/7/semi.tex						\
	../slides/7/kurven.tex						\
	../slides/7/einparameter.tex					\
	../slides/7/ableitung.tex					\
	../slides/7/liealgebra.tex					\
	../slides/7/kommutator.tex					\
	../slides/7/dg.tex						\
	../slides/7/zusammenhang.tex					\
	../slides/7/quaternionen.tex					\
	../slides/7/qdreh.tex						\
	../slides/7/ueberlagerung.tex					\
	../slides/7/hopf.tex						\
	../slides/7/haar.tex						\
	../slides/7/chapter.tex

