#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-clifford =						\
	papers/clifford/packages.tex					\
	papers/clifford/main.tex					\
	papers/clifford/references.bib				\
	papers/clifford/teil0.tex					\
	papers/clifford/teil1.tex					\
	papers/clifford/teil2.tex					\
	papers/clifford/teil3.tex

