#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-clifford =							\
	papers/clifford/packages.tex					\
	papers/clifford/main.tex					\
	papers/clifford/references.bib					\
	papers/clifford/0_ElevatorPitch.tex				\
	papers/clifford/1_Vektordarstellung.tex				\
	papers/clifford/2_QuadratVektoren.tex				\
	papers/clifford/3_MultiplikationVektoren.tex			\
	papers/clifford/4_GeometrischesProdukt.tex			\
	papers/clifford/5_PolareDarstellung.tex				\
	papers/clifford/6_Dirac-Matrizen.tex				\
	papers/clifford/7_Reflektion.tex				\
	papers/clifford/8_Rotation.tex					\
	papers/clifford/9_KomplexeZahlen.tex				\
	papers/clifford/10_Quaternionen.tex
