#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/80-wahrscheinlichkeit/google.tex			\
	chapters/80-wahrscheinlichkeit/markov.tex			\
	chapters/80-wahrscheinlichkeit/positiv.tex			\
	chapters/80-wahrscheinlichkeit/parrondo.tex			\
	chapters/80-wahrscheinlichkeit/uebungsaufgaben/8001.tex		\
	chapters/80-wahrscheinlichkeit/chapter.tex
