#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-reedsolomon =						\
	papers/reedsolomon/packages.tex					\
	papers/reedsolomon/main.tex					\
	papers/reedsolomon/einleitung.tex				\
	papers/reedsolomon/idee.tex					\
	papers/reedsolomon/dtf.tex					\
	papers/reedsolomon/endlichekoerper.tex				\
	papers/reedsolomon/codebsp.tex					\
	papers/reedsolomon/decohnefehler.tex				\
	papers/reedsolomon/decmitfehler.tex				\
	papers/reedsolomon/rekonstruktion.tex				\
	papers/reedsolomon/zusammenfassung.tex				\
	papers/reedsolomon/anwendungen.tex				\
	papers/reedsolomon/hilfstabellen.tex				\
	papers/reedsolomon/references.bib				


