#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-reedsolomon =						\
	papers/reedsolomon/packages.tex					\
	papers/reedsolomon/main.tex					\
	papers/reedsolomon/references.bib				\
	papers/reedsolomon/teil0.tex					\
	papers/reedsolomon/teil1.tex					\
	papers/reedsolomon/teil2.tex					\
	papers/reedsolomon/teil3.tex

