#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/70-graphen/beschreibung.tex				\
	chapters/70-graphen/spektral.tex				\
	chapters/70-graphen/wavelets.tex				\
	chapters/70-graphen/chapter.tex
