#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, Hochschule Rapperswil
#
include ../slides/0/Makefile.inc
include ../slides/1/Makefile.inc
include ../slides/2/Makefile.inc
include ../slides/3/Makefile.inc
include ../slides/4/Makefile.inc
include ../slides/5/Makefile.inc
include ../slides/8/Makefile.inc

slides = 								\
	$(chapter0) $(chapter1) $(chapter2) $(chapter3) $(chapter4)	\
	$(chapter5) $(chapter8)
