#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, Hochschule Rapperswil
#
include ../slides/0/Makefile.inc
include ../slides/1/Makefile.inc

slides = 								\
	$(chapter0) $(chapter1)
