
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter8 =								\
	../slides/8/dgraph.tex						\
	../slides/8/graph.tex						\
	../slides/8/grad.tex						\
	../slides/8/inzidenz.tex					\
	../slides/8/inzidenzd.tex					\
	../slides/8/diffusion.tex					\
	../slides/8/laplace.tex						\
	../slides/8/produkt.tex						\
	../slides/8/fourier.tex						\
	../slides/8/spanningtree.tex					\
	../slides/8/pfade/adjazenz.tex					\
	../slides/8/pfade/langepfade.tex				\
	../slides/8/pfade/beispiel.tex					\
	../slides/8/pfade/gf.tex					\
	../slides/8/floyd-warshall/problem.tex				\
	../slides/8/floyd-warshall/rekursion.tex			\
	../slides/8/floyd-warshall/iteration.tex			\
	../slides/8/floyd-warshall/wegiteration.tex			\
	../slides/8/floyd-warshall/wege.tex				\
	../slides/8/tokyo/google.tex					\
	../slides/8/tokyo/bahn0.tex					\
	../slides/8/tokyo/bahn1.tex					\
	../slides/8/tokyo/bahn2.tex					\
	../slides/8/chrind.tex						\
	../slides/8/chrindprop.tex					\
	../slides/8/chroma1.tex						\
	../slides/8/amax.tex						\
	../slides/8/subgraph.tex					\
	../slides/8/chrwilf.tex						\
	../slides/8/weitere.tex						\
	../slides/8/wavelets/funktionen.tex				\
	../slides/8/wavelets/laplacebasis.tex				\
	../slides/8/wavelets/vektoren.tex				\
	../slides/8/chapter.tex

