
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter8 =								\
	../slides/8/dgraph.tex						\
	../slides/8/graph.tex						\
	../slides/8/grad.tex						\
	../slides/8/inzidenz.tex					\
	../slides/8/inzidenzd.tex					\
	../slides/8/chapter.tex

