#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-munkres =						\
	papers/munkres/packages.tex					\
	papers/munkres/main.tex					\
	papers/munkres/references.bib				\
	papers/munkres/teil0.tex					\
	papers/munkres/teil1.tex					\
	papers/munkres/teil2.tex					\
	papers/munkres/teil3.tex

