#
# Makefile -- build images for crypto chapter
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	dh.pdf elliptic.pdf

dh.pdf:	dh.tex
	pdflatex dh.tex

elliptic.pdf:	elliptic.tex
	pdflatex elliptic.tex

