#
# Makefile -- build images for crypto chapter
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	dh.pdf elliptic.pdf schieberegister.pdf multiplikation.pdf sbox.pdf \
	shift.pdf

dh.pdf:	dh.tex
	pdflatex dh.tex

elliptic.pdf:	elliptic.tex
	pdflatex elliptic.tex

schieberegister.pdf:	schieberegister.tex
	pdflatex schieberegister.tex

multiplikation.pdf:	multiplikation.tex
	pdflatex multiplikation.tex

sbox.pdf:	sbox.tex
	pdflatex sbox.tex

shift.pdf:	shift.tex
	pdflatex shift.tex

