#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/40-eigenwerte/numerisch.tex				\
	chapters/40-eigenwerte/normalformen.tex				\
	chapters/40-eigenwerte/grundlagen.tex				\
	chapters/40-eigenwerte/spektralradius.tex			\
	chapters/40-eigenwerte/spektraltheorie.tex			\
	chapters/40-eigenwerte/uebungsaufgaben/4001.tex			\
	chapters/40-eigenwerte/uebungsaufgaben/4002.tex			\
	chapters/40-eigenwerte/uebungsaufgaben/4003.tex			\
	chapters/40-eigenwerte/uebungsaufgaben/4004.tex			\
	chapters/40-eigenwerte/uebungsaufgaben/4005.tex			\
	chapters/40-eigenwerte/chapter.tex
