#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	binomial2.pdf binomial5.pdf fermat.pdf

binomial2.pdf:	binomial2.tex
	pdflatex binomial2.tex

binomial5.pdf:	binomial5.tex farben.tex
	pdflatex binomial5.tex

fermat.pdf:	fermat.tex
	pdflatex fermat.tex

