#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chaosspiel.pdf:	chaosspiel.tex					\
	farnnotweight-eps-converted-to.pdf			\
	farnrightwight-eps-converted-to.pdf
	pdflatex chaosspiel.tex
