#
# Makefile -- Bilder für Kapitel Graphen
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	peterson.pdf adjazenzu.pdf adjazenzd.pdf kreis.pdf

peterson.pdf:	peterson.tex
	pdflatex peterson.tex

adjazenzu.pdf:	adjazenzu.tex
	pdflatex adjazenzu.tex

adjazenzd.pdf:	adjazenzd.tex
	pdflatex adjazenzd.tex

kreis.pdf:	kreis.tex
	pdflatex kreis.tex

