#
# Makefile -- Bilder für Kapitel Graphen
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	peterson.pdf adjazenzu.pdf

peterson.pdf:	peterson.tex
	pdflatex peterson.tex

adjazenzu.pdf:	adjazenzu.tex
	pdflatex adjazenzu.tex

