
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter4 =								\
	../slides/4/ggt.tex						\
	../slides/4/euklidmatrix.tex					\
	../slides/4/euklidbeispiel.tex					\
	../slides/4/euklidtabelle.tex					\
	../slides/4/fp.tex						\
	../slides/4/division.tex					\
	../slides/4/gauss.tex						\
	../slides/4/dh.tex						\
	../slides/4/divisionpoly.tex					\
	../slides/4/euklidpoly.tex					\
	../slides/4/polynomefp.tex					\
	../slides/4/schieberegister.tex					\
	../slides/4/charakteristik.tex					\
	../slides/4/char2.tex						\
	../slides/4/frobenius.tex					\
	../slides/4/qundr.tex						\
	../slides/4/alpha.tex						\
	../slides/4/galois/erweiterung.tex				\
	../slides/4/galois/automorphismus.tex				\
	../slides/4/galois/konstruktion.tex				\
	../slides/4/galois/wuerfel.tex					\
	../slides/4/galois/winkeldreiteilung.tex			\
	../slides/4/galois/quadratur.tex				\
	../slides/4/galois/radikale.tex					\
	../slides/4/galois/aufloesbarkeit.tex				\
	../slides/4/galois/sn.tex					\
	../slides/4/chapter.tex


