#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-verkehr =						\
	papers/verkehr/packages.tex					\
	papers/verkehr/main.tex					\
	papers/verkehr/references.bib				\
	papers/verkehr/teil0.tex					\
	papers/verkehr/teil1.tex					\
	papers/verkehr/teil2.tex					\
	papers/verkehr/teil3.tex

