#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-verkehr =							\
	papers/verkehr/packages.tex					\
	papers/verkehr/main.tex						\
	papers/verkehr/section1.tex					\
	papers/verkehr/section2.tex					\
	papers/verkehr/references.bib

