#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	homocycles.pdf homoboundaries.pdf homoclasses.pdf gausshomoex.pdf gausshomobasis.pdf dreieck.pdf polyeder.pdf

dreieck.pdf:	dreieck.tex
	pdflatex dreieck.tex

polyeder.pdf:	polyeder.tex
	pdflatex polyeder.tex

gausshomobasis.pdf:	gausshomobasis.tex
	pdflatex gausshomobasis.tex

gausshomoex.pdf:	gausshomoex.tex
	pdflatex gausshomoex.tex

homocycles.pdf:	homocycles.tex
	pdflatex homocycles.tex

homoboundaries.pdf:	homoboundaries.tex
	pdflatex homoboundaries.tex

homoclasses.pdf:	homoclasses.tex
	pdflatex homoclasses.tex

