#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	dreieck.pdf polyeder.pdf

dreieck.pdf:	dreieck.tex
	pdflatex dreieck.tex

polyeder.pdf:	polyeder.tex
	pdflatex polyeder.tex

