#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/30-endlichekoerper/chapter.tex
