#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/30-endlichekoerper/uebungsaufgaben/3001.tex		\
	chapters/30-endlichekoerper/uebungsaufgaben/3002.tex		\
	chapters/30-endlichekoerper/uebungsaufgaben/3003.tex		\
	chapters/30-endlichekoerper/uebungsaufgaben/3004.tex		\
	chapters/30-endlichekoerper/uebungsaufgaben/3005.tex		\
	chapters/30-endlichekoerper/euklid.tex				\
	chapters/30-endlichekoerper/galois.tex				\
	chapters/30-endlichekoerper/wurzeln.tex				\
	chapters/30-endlichekoerper/chapter.tex
