
#
# Makefile.inc -- additional depencencies
#
# (c) 20920 Prof Dr Andreas Müller, Hochschule Rapperswil
#
chapter0 =								\
	../slides/0/was.tex						\
	../slides/0/intro.tex						\
	../slides/0/resourcen.tex					\
	../slides/0/latextipps.tex					\
	../slides/0/nextsteps.tex					\
	../slides/0/themen1.tex						\
	../slides/0/themen2.tex						\
	../slides/0/themen3.tex						\
	../slides/0/chapter.tex

