#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-multiplikation =						\
	papers/multiplikation/packages.tex					\
	papers/multiplikation/main.tex					\
	papers/multiplikation/references.bib				\
	papers/multiplikation/einlteung.tex					\
	papers/multiplikation/loesungsmethoden.tex					\
	papers/multiplikation/problemstellung.tex					

