#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-multiplikation =						\
	papers/multiplikation/packages.tex					\
	papers/multiplikation/main.tex					\
	papers/multiplikation/references.bib				\
	papers/multiplikation/teil0.tex					\
	papers/multiplikation/teil1.tex					\
	papers/multiplikation/teil2.tex					\
	papers/multiplikation/teil3.tex

