
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter2 =								\
	../slides/2/norm.tex						\
	../slides/2/skalarprodukt.tex					\
	../slides/2/cauchyschwarz.tex					\
	../slides/2/chapter.tex

