
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter2 =								\
	../slides/2/norm.tex						\
	../slides/2/skalarprodukt.tex					\
	../slides/2/cauchyschwarz.tex					\
	../slides/2/polarformel.tex					\
	../slides/2/funktionenraum.tex					\
	../slides/2/operatornorm.tex					\
	../slides/2/linearformnormen.tex				\
	../slides/2/funktionenalgebra.tex				\
	../slides/2/frobeniusnorm.tex					\
	../slides/2/frobeniusanwendung.tex				\
	../slides/2/quotient.tex					\
	../slides/2/quotientv.tex					\
	../slides/2/chapter.tex

