#
# Makefile.inc -- Makefile dependencies for chapter 0
#
# (c) 2020 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/00-einleitung/chapter.tex
