#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chaptera =								\
	../slides/a/dc/prinzip.tex					\
	../slides/a/dc/effizient.tex					\
	../slides/a/dc/beispiel.tex					\
									\
	../slides/a/ecc/gruppendh.tex					\
	../slides/a/ecc/kurve.tex					\
	../slides/a/ecc/inverse.tex					\
	../slides/a/ecc/operation.tex					\
	../slides/a/ecc/quadrieren.tex					\
	../slides/a/ecc/oakley.tex					\
									\
	../slides/a/aes/bytes.tex					\
	../slides/a/aes/sinverse.tex					\
	../slides/a/aes/blocks.tex					\
	../slides/a/aes/keys.tex					\
	../slides/a/aes/runden.tex					\
									\
	../slides/a/chapter.tex

