
#
# Makefile.inc -- additional depencencies
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chaptera =								\
	../slides/a/dc/prinzip.tex					\
	../slides/a/dc/effizient.tex					\
	../slides/a/dc/beispiel.tex					\
	../slides/a/chapter.tex

