
#
# Makefile.inc -- additional depencencies
#
# (c) 20920 Prof Dr Andreas Müller, Hochschule Rapperswil
#
chapter1 =								\
	../slides/1/zahlensysteme.tex					\
	../slides/1/peano.tex						\
	../slides/1/ganz.tex						\
	../slides/1/bruch.tex						\
	../slides/1/strukturen.tex					\
	../slides/1/j.tex						\
	../slides/1/vektorraum.tex					\
	../slides/1/matrixalgebra.tex					\
	../slides/1/algebrastruktur.tex					\
	../slides/1/speziell.tex					\
	../slides/1/dreieck.tex						\
	../slides/1/hadamard.tex					\
	../slides/1/chapter.tex

