#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/60-gruppen/symmetrien.tex				\
	chapters/60-gruppen/lie-gruppen.tex				\
	chapters/60-gruppen/lie-algebren.tex				\
	chapters/60-gruppen/homogen.tex					\
	chapters/60-gruppen/uebungsaufgaben/6001.tex			\
	chapters/60-gruppen/uebungsaufgaben/6002.tex			\
	chapters/60-gruppen/uebungsaufgaben/6003.tex			\
	chapters/60-gruppen/chapter.tex
