#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all: standard.pdf messrauschen_geaendert.pdf prozessrauschen_geaendert.pdf

standard.pdf: standard.tex
	pdflatex standard.tex

messrauschen_geaendert.pdf: messrauschen_geaendert.tex
	pdflatex messrauschen_geaendert.tex

prozessrauschen_geaendert.pdf: prozessrauschen_geaendert.tex
	pdflatex prozessrauschen_geaendert.tex
