#
# Makefile.inc -- Makefile dependencies for chapter 10
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/95-homologie/simplex.tex				\
	chapters/95-homologie/komplex.tex				\
	chapters/95-homologie/homologie.tex				\
	chapters/95-homologie/homologieketten.tex			\
	chapters/95-homologie/basiswahl.tex				\
	chapters/95-homologie/fixpunkte.tex				\
	chapters/95-homologie/eulerchar.tex				\
	chapters/95-homologie/induzierteabb.tex				\
	chapters/95-homologie/chapter.tex







